name: stream_disposable
description: Package to help disposing Stream Subscriptions and Sink objects
version: 2.0.0
homepage: https://github.com/Vanethos/stream_disposable
issue_tracker: https://github.com/Vanethos/stream_disposable/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
